require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StancesController do
  render_views

  # This should return the minimal set of attributes required to create a valid
  # Stance. As you add validations to Stance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "participant_id" => "1", "supporting" => "1", "statement" => "502" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StancesController. Be sure to keep this updated too.
  let(:session_id) { "woo" }
  let(:valid_session) { {:session_id => session_id} }

  before(:each) do
    sign_in
  end

  describe "GET index" do
    it "assigns all stances as @stances" do
      stance = Stance.create! valid_attributes
      get :index, {}, valid_session
      assigns(:stances).should eq([stance])
    end
  end

  describe "GET show" do
    it "assigns the requested stance as @stance" do
      stance = Stance.create! valid_attributes
      get :show, {:id => stance.to_param}, valid_session
      assigns(:stance).should eq(stance)
    end
  end

  describe "GET new" do
    it "assigns a new stance as @stance" do
      get :new, {}, valid_session
      assigns(:stance).should be_a_new(Stance)
    end
  end

  describe "GET edit" do
    it "assigns the requested stance as @stance" do
      stance = Stance.create! valid_attributes
      get :edit, {:id => stance.to_param}, valid_session
      assigns(:stance).should eq(stance)
    end
  end

  describe "POST create" do
    before(:each) do
      FactoryGirl.create(:participant, :session_id => session_id)
    end

    describe "with valid params" do
      it "creates a new Stance" do
        expect {
          post :create, {:stance => valid_attributes}, valid_session
        }.to change(Stance, :count).by(1)
      end

      it "assigns a newly created stance as @stance" do
        post :create, {:stance => valid_attributes}, valid_session
        assigns(:stance).should be_a(Stance)
        assigns(:stance).should be_persisted
      end

      it "redirects to the created stance" do
        post :create, {:stance => valid_attributes}, valid_session
        response.should redirect_to(goodbye_path)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved stance as @stance" do
        # Trigger the behavior that occurs when invalid params are submitted
        Stance.any_instance.stub(:save).and_return(false)
        post :create, {:stance => { "participant_id" => "invalid value" }}, valid_session
        assigns(:stance).should be_a_new(Stance)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Stance.any_instance.stub(:save).and_return(false)
        post :create, {:stance => { "participant_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    before(:each) do
      FactoryGirl.create(:participant, :session_id => session_id)
    end

    describe "with valid params" do
      it "updates the requested stance" do
        stance = Stance.create! valid_attributes
        # Assuming there are no other stances in the database, this
        # specifies that the Stance created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Stance.any_instance.should_receive(:update).with({ "supporting" => "1" })
        put :update, {:id => stance.to_param, :stance => { "supporting" => "1" }}, valid_session
      end

      it "assigns the requested stance as @stance" do
        stance = Stance.create! valid_attributes
        put :update, {:id => stance.to_param, :stance => valid_attributes}, valid_session
        assigns(:stance).should eq(stance)
      end

      it "redirects to the stance" do
        stance = Stance.create! valid_attributes
        put :update, {:id => stance.to_param, :stance => valid_attributes}, valid_session
        response.should redirect_to(goodbye_path)
      end
    end

    describe "with invalid params" do
      it "assigns the stance as @stance" do
        stance = Stance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Stance.any_instance.stub(:save).and_return(false)
        put :update, {:id => stance.to_param, :stance => { "participant_id" => "invalid value" }}, valid_session
        assigns(:stance).should eq(stance)
      end

      it "re-renders the 'edit' template" do
        stance = Stance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Stance.any_instance.stub(:save).and_return(false)
        put :update, {:id => stance.to_param, :stance => { "participant_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested stance" do
      stance = Stance.create! valid_attributes
      expect {
        delete :destroy, {:id => stance.to_param}, valid_session
      }.to change(Stance, :count).by(-1)
    end

    it "redirects to the stances list" do
      stance = Stance.create! valid_attributes
      delete :destroy, {:id => stance.to_param}, valid_session
      response.should redirect_to(stances_url)
    end
  end

end
